## Ejercicio obligatorio
### Advertising

In [7]:
import pandas as pd
import numpy as np

# import file
df = pd.read_csv('../../res/tp4/Advertising.csv', sep=',')  # 200 rows
df = df[['TV', 'Radio', 'Newspaper', 'Sales']]
column_count = len(list(df))

df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [13]:
means = df.mean()
covariance = np.zeros((column_count, column_count))

def calc_sum(col1, col2):
    return sum(map(lambda tupl: (tupl[1][col1] - means[col1]) * (tupl[1][col2] - means[col2]), df.iterrows()))

for i, col1 in enumerate(list(df)):
    for k, col2 in enumerate(list(df)):
        if i > k:
            continue
        s_ik = 1 / column_count * calc_sum(col1, col2)
        covariance[i][k] = covariance[k][i] = s_ik

print(covariance)

[[366704.7571875   3475.659       5269.49275    17431.9121875]
 [  3475.659      10966.2802      5696.2247      2220.6255   ]
 [  5269.49275     5696.2247     23596.8392      1290.58425  ]
 [ 17431.9121875   2220.6255      1290.58425     1354.2871875]]


In [14]:
import math

correlation = np.zeros((column_count, column_count))

for i, col1 in enumerate(list(df)):
    for k, col2 in enumerate(list(df)):
        if i > k:
            continue
        s_ik = covariance[i][k]
        s_ii = covariance[i][i]
        s_kk = covariance[k][k]
        correlation[i][k] = correlation[k][i] = s_ik / (math.sqrt(s_ii) * math.sqrt(s_kk))

print(correlation)

[[1.         0.05480866 0.05664787 0.78222442]
 [0.05480866 1.         0.35410375 0.57622257]
 [0.05664787 0.35410375 1.         0.22829903]
 [0.78222442 0.57622257 0.22829903 1.        ]]
